# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0002_sayhello_locat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SayHello',
            new_name='SayHelloToMe',
        ),
    ]
