# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0003_auto_20180627_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayhellotome',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
