# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0004_sayhellotome_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sayhellotome',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='sayhellotome',
            name='category',
            field=models.CharField(choices=[('soup', 'soup'), ('pizza', 'pizza'), ('sand', 'sandwich'), ('drink', 'drink')], default='pizza', max_length=5),
        ),
    ]
