# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0005_auto_20180627_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SayHelloToMe',
            new_name='FaveRest',
        ),
    ]
