# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0006_auto_20180627_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faverest',
            name='category',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='pizza', max_length=5),
        ),
    ]
