# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0008_auto_20180627_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='faverest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faverest',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='faverest',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
