# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0013_auto_20180627_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faverest',
            name='category',
            field=models.CharField(choices=[('soup', (('onso', 'oniensoup'), ('joso', 'soupjo'))), ('pizza', (('makhp', 'makhsus'), ('peppi', 'peperoni'))), ('sand', 'sandwich'), ('drink', 'drink')], default='drink', max_length=5),
        ),
    ]
