# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-28 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0014_auto_20180627_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='faverest',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
